version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bun-graphql
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6382:6379
volumes:
  db_data:
