version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bun-graphql
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
